# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content_url',
            new_name='url',
        ),
    ]
