# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-15 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20161015_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='url',
            field=models.URLField(),
        ),
    ]
